name = "Horrifying Industry"
author = "Nitro"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e82291610457598982095c8a8f0c1d372cdd8236a6e1b875fde1203ef35da3f9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
