name = "Horrifying Industry"
author = "Nitro"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a66f0e06773e25619e200596891878aa924d40efc5acd80d88a5d8cb93c96083"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
