name = "Horrifying Industry"
author = "Nitro"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5f8f490d50ad25a939dabaf3e73c44706c176bb0815bfe4d1cf6524dfc2c90"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
