filename = 'the_obsessed-1.5c-forge-1.20.1.jar'
name = 'The Obsessed - Advanced Psychological Horror, Mysterious Arachnid Stalker'
side = 'server'
x-prismlauncher-loaders = [ 'forge' ]
x-prismlauncher-mc-versions = [ '1.20.1' ]
x-prismlauncher-release-type = 'release'
x-prismlauncher-version-number = 'the_obsessed-1.5c-forge-1.20.1.jar'

[download]
hash = '36f84f89231d30571d010f3cc68c0ac8dcb9fbb2'
hash-format = 'sha1'
mode = 'metadata:curseforge'
url = ''

[update.curseforge]
file-id = 8148569
project-id = 1372373

[[x-prismlauncher-dependencies]]
addonId = '967672'
type = 'OPTIONAL'

[[x-prismlauncher-dependencies]]
addonId = '388172'
type = 'REQUIRED'